[dependencies]
core = {}
alloc = {}

[dependencies.compiler_builtins]
features = ["mem"]
stage = 1

[dependencies.std]
git = "https://github.com/japaric/steed"
stage = 2

[dependencies.test]
git = "https://github.com/japaric/steed"
stage = 3
